# Generated by Django 3.2.6 on 2021-08-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя и фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша почта')),
                ('telephone', models.CharField(max_length=20, verbose_name='Ваш номер телефона')),
                ('university', models.CharField(max_length=50, verbose_name='Ваш Университет')),
                ('discipline', models.CharField(max_length=50, verbose_name='Дисциплина, в котором нуждаетесь в менторе')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Дисциплина вопроса')),
                ('task', models.TextField(verbose_name='Ваш вопрос')),
            ],
        ),
    ]
